# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
  
jobs:

  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Connector code generation from ballerina OpenAPI tool
        run:  echo Connector code generated
      
      - name: Change the directory to the connector code directory
        run: cd connector1/v0.0.1

      - name: Connector build
        uses: ballerina-platform/ballerina-action/@master
        with:
          args: 
            build -c ./connector1/v0.0.1/
      - name: Push the connector to Ballerina Central
        uses: ballerina-platform/ballerina-action/@master
        with:
          env: 
            BALLERINA_CENTRAL_ACCESS_TOKEN = ${{ secrets.BALLERINATOKEN }}
          args: 
            push 
          
          
